// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN8g1tII_WPtUpZiAFWWJRy12x-o_A654',
    appId: '1:426439320072:web:2e601d87916c7b0a58a7bd',
    messagingSenderId: '426439320072',
    projectId: 'grpr-a5e9f',
    authDomain: 'grpr-a5e9f.firebaseapp.com',
    storageBucket: 'grpr-a5e9f.firebasestorage.app',
    measurementId: 'G-KF0TVPG6X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMCJeLxEbcbL6b-skBE2OCJqTE0Xvj1E',
    appId: '1:426439320072:android:020e361845432fd258a7bd',
    messagingSenderId: '426439320072',
    projectId: 'grpr-a5e9f',
    storageBucket: 'grpr-a5e9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYvIv5R0sTGbs0Ae25jcPEbbGz75GkCAM',
    appId: '1:426439320072:ios:2ce4b660f88eb44b58a7bd',
    messagingSenderId: '426439320072',
    projectId: 'grpr-a5e9f',
    storageBucket: 'grpr-a5e9f.firebasestorage.app',
    iosBundleId: 'com.example.drawer',
  );
}
